### PR TITLE
Set default to 4 spaces

### PR DESCRIPTION
**Pull request by Parker8283**
Three just seems weird to me, plus, for our purposes, we will be using 4, so best to just set that as the default.

I can't squash the commits right now, so I'll let you know when I've squashed them. That or you can just do this yourself and close this :P

### CODE REVIEW

**Comment by LexManos** [comment]
No, but adding a option to change the default may be accepted.
This also derps up our existing regexs in FFFixer.

**Comment by Parker8283** [comment]
That option already exists, so I guess just add it to the args in FG.

**Comment by AbrarSyed** [comment]
We can always change the existing regexes...

**Comment by LexManos** [comment]
i dont see why we would.
Our toolchain works just fine now.
Now, in 1.3 when we switch over to this FF and it breaks things THEN we can think about this.

**Comment by Parker8283** [comment]
So if we're not using this FF until 1.3, then it would be safe to make these kinds of changes?

**Comment by LexManos** [comment]
No, we also have to keep respect that this isn't our project.
There is no need to make this change to the code itself, we could just use the command parameter.
The point of forking this was so that we could push it as a library on our maven, and fix any bugs that we run into when decompiling java 8.

As a side note, why do you even want this? It's just a code style issue, which is moot considering we run astyle after it.

**Comment by Parker8283** [comment]
Because I use FF on other projects, ones that I don't run through Astyle, and thought that the 3 space indentation was weird. I figured since we'd be decompiling with this soon, we would take some of the work out of Astyle's hands and fix the indentation ourselves. But you make a good point. In the end, it just comes down to my laziness and not wanting to specify the indentation each time I run this.

**Pull request closed without merging**
